{% set name = "pytest-services" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 2da740487d08ea63dfdf718f5d4ba11e590c99ddf5481549edebf7a3a42ca536
  - folder: src
    url: https://github.com/pytest-dev/pytest-services/archive/{{ version }}.tar.gz
    sha256: 9f12a244baa5da24a8d40af7c59a02b7e1f63aa9efc4e682efb43d0e291fc4d1

build:
  number: 2
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - psutil
    - pytest
    - python
    - requests
    - setuptools
    - subprocess32  # [py2k]
    - zc.lockfile >=2.0

test:
  source_files:
    - src/tests
  requires:
    - astroid
    - coverage
    - mock
    - mysqlclient  # [unix]
    - pip
    - pylibmc  # [unix]
    - pytest-pep8
  imports:
    - pytest_services
  commands:
    - python -m pip check
    - cd src && pytest -vv -k "not xvfb and not mysql and not memcached"  # [unix]

about:
  home: https://github.com/pytest-dev/pytest-services
  license: MIT
  license_family: MIT
  license_file: src/LICENSE.txt
  summary: Collection of fixtures and utility functions to run service processes for your tests

extra:
  recipe-maintainers:
    - bollwyvl
