{% set name = "pytest-services" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: ecdbee4b0cd7d4e9d84ce43d47e45c07fd5aec84d594c961c8c1c98d04c95349
  - folder: src
    url: https://github.com/pytest-dev/pytest-services/archive/{{ version }}.tar.gz
    sha256: e4085311a023d2f3b979ff03d6f744711bdfad93aed5fe1467ff9b18f0a3fa4e

build:
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - psutil
    - pytest
    - python
    - requests
    - setuptools
    - subprocess32  # [py2k]
    - zc.lockfile >=2.0

test:
  source_files:
    - src/tests
  requires:
    - astroid
    - coverage
    - mock
    - mysqlclient  # [unix]
    - pip
    - pylibmc  # [unix]
    - pytest-pep8
  imports:
    - pytest_services
  commands:
    - python -m pip check
    - cd src && pytest -vv -k "not xvfb and not mysql and not memcached"  # [unix]

about:
  home: https://github.com/pytest-dev/pytest-services
  license: MIT
  license_family: MIT
  license_file: src/LICENSE.txt
  summary: Collection of fixtures and utility functions to run service processes for your tests

extra:
  recipe-maintainers:
    - bollwyvl
