{% set version = "2.2.1" %}

package:
  name: pytest-services
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/p/pytest-services/pytest-services-{{ version }}.tar.gz
    sha256: 2da740487d08ea63dfdf718f5d4ba11e590c99ddf5481549edebf7a3a42ca536
  - folder: src
    url: https://github.com/pytest-dev/pytest-services/archive/{{ version }}.tar.gz
    sha256: 9f12a244baa5da24a8d40af7c59a02b7e1f63aa9efc4e682efb43d0e291fc4d1

build:
  noarch: python
  number: 4
  script:
    - cd dist
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - psutil
    - pytest
    - python >={{ python_min }}
    - requests
    - setuptools
    - zc.lockfile >=2.0

test:
  source_files:
    - src/tests
  requires:
    - astroid
    - coverage
    - mock
    - mysqlclient  # [unix]
    - pip
    - pylibmc  # [unix]
    - pytest-pep8
    - python {{ python_min }}
  imports:
    - pytest_services
  commands:
    - pip check
    - cd src 
    - pytest -vv -k "not xvfb and not mysql and not memcached"  # [unix]

about:
  home: https://github.com/pytest-dev/pytest-services
  license: MIT
  license_family: MIT
  license_file: src/LICENSE.txt
  summary: Collection of fixtures and utility functions to run service processes for your tests

extra:
  recipe-maintainers:
    - bollwyvl
